import { MemoryTier } from "../runtime/types.js";
import type { AgentContract } from "../runtime/types.js";

export const marketScannerContract: AgentContract = {
  agent_name: "market_scanner",
  agent_class: "intelligence",
  version: "1.0.0",
  capabilities: [
    "collect_market_signals",
    "competitor_monitoring",
    "trend_identification",
  ],
  input_schema: "ScanRequest",
  output_schema: "SignalBatch",
  memory_read_tiers: [MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["web_search", "rss_reader", "job_board_api", "competitor_tracker"],
  cost_ceiling_usd: 5,
  timeout_ms: 120000,
  retry_policy: { max_attempts: 3, backoff: "exponential" },
  fallback_policy: "partial_source_success_allowed",
  validation_policy: "require_source_url_or_trace",
  escalation_policy: "p2_if_all_sources_fail",
};

export const painDetectorContract: AgentContract = {
  agent_name: "pain_detector",
  agent_class: "intelligence",
  version: "1.0.0",
  capabilities: [
    "signal_to_pain_conversion",
    "buyer_identification",
    "workaround_detection",
  ],
  input_schema: "SignalBatch",
  output_schema: "PainCandidateList",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["llm_gateway"],
  cost_ceiling_usd: 3,
  timeout_ms: 90000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "send_to_human_review",
  validation_policy: "each_pain_requires_evidence_buyer_and_current_workaround",
  escalation_policy: "p2_if_zero_candidates",
};

export const opportunityValidatorContract: AgentContract = {
  agent_name: "opportunity_validator",
  agent_class: "strategy",
  version: "1.0.0",
  capabilities: [
    "pain_scoring",
    "urgency_assessment",
    "willingness_to_pay_estimation",
    "competition_analysis",
  ],
  input_schema: "PainCandidate",
  output_schema: "OpportunityScore",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["llm_gateway", "market_data_tool"],
  cost_ceiling_usd: 4,
  timeout_ms: 90000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "mark_low_confidence",
  validation_policy: "require_raw_scores_confidence_and_evidence_links",
  escalation_policy: "p1_if_high_score_low_confidence",
};

export const economicAnalystContract: AgentContract = {
  agent_name: "economic_analyst",
  agent_class: "strategy",
  version: "1.0.0",
  capabilities: [
    "expected_value_estimation",
    "roi_calculation",
    "risk_adjusted_analysis",
  ],
  input_schema: "OpportunityOrPlan",
  output_schema: "EconomicScorecard",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["pricing_db", "revenue_ledger", "llm_gateway"],
  cost_ceiling_usd: 3,
  timeout_ms: 90000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "require_human_estimate",
  validation_policy: "require_revenue_cost_probability_and_risk",
  escalation_policy: "p0_if_blast_radius_critical",
};

export const smePanelCoordinatorContract: AgentContract = {
  agent_name: "sme_panel_coordinator",
  agent_class: "deliberation",
  version: "1.0.0",
  capabilities: [
    "cross_functional_review",
    "consensus_building",
    "risk_synthesis",
  ],
  input_schema: "OpportunityScore",
  output_schema: "SMEConsensus",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["llm_gateway"],
  cost_ceiling_usd: 8,
  timeout_ms: 180000,
  retry_policy: { max_attempts: 1, backoff: "none" },
  fallback_policy: "route_to_founder",
  validation_policy: "require_minority_risks",
  escalation_policy: "p1_if_no_consensus",
};

export const productSpecWriterContract: AgentContract = {
  agent_name: "product_spec_writer",
  agent_class: "product",
  version: "1.0.0",
  capabilities: [
    "spec_generation",
    "acceptance_criteria_definition",
    "revenue_path_documentation",
  ],
  input_schema: "ApprovedOpportunity",
  output_schema: "ProductSpec",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M2],
  allowed_tools: ["llm_gateway", "docs_lookup"],
  cost_ceiling_usd: 5,
  timeout_ms: 120000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "human_spec_review",
  validation_policy: "require_user_acceptance_criteria_metrics_and_revenue_path",
  escalation_policy: "p1_if_spec_incomplete_after_repair",
};

export const taskGraphBuilderContract: AgentContract = {
  agent_name: "task_graph_builder",
  agent_class: "planning",
  version: "1.0.0",
  capabilities: [
    "dependency_graph_construction",
    "task_decomposition",
    "dag_validation",
  ],
  input_schema: "ProductSpec",
  output_schema: "TaskGraph",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["llm_gateway"],
  cost_ceiling_usd: 2,
  timeout_ms: 60000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "serial_task_plan",
  validation_policy: "no_cycles_all_dependencies_resolved",
  escalation_policy: "p1_if_invalid_dag",
};

export const builderAgentContract: AgentContract = {
  agent_name: "builder_agent",
  agent_class: "execution",
  version: "1.0.0",
  capabilities: [
    "code_generation",
    "script_execution",
    "asset_production",
    "documentation_generation",
  ],
  input_schema: "TaskNode",
  output_schema: "ArtifactBundle",
  memory_read_tiers: [MemoryTier.M0, MemoryTier.M1, MemoryTier.M2],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M4],
  allowed_tools: ["filesystem", "code_runner", "package_manager", "llm_gateway"],
  cost_ceiling_usd: 10,
  timeout_ms: 300000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "split_task_and_retry",
  validation_policy: "artifact_manifest_required",
  escalation_policy: "p1_if_build_blocked",
};

export const qaRepairAgentContract: AgentContract = {
  agent_name: "qa_repair_agent",
  agent_class: "validation",
  version: "1.0.0",
  capabilities: [
    "artifact_validation",
    "defect_identification",
    "localized_repair",
    "qa_verdict_production",
  ],
  input_schema: "ArtifactBundle",
  output_schema: "QAVerdict",
  memory_read_tiers: [MemoryTier.M0, MemoryTier.M1, MemoryTier.M2, MemoryTier.M5],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M5],
  allowed_tools: ["test_runner", "schema_validator", "lint_runner", "llm_gateway"],
  cost_ceiling_usd: 6,
  timeout_ms: 180000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "escalate_with_failure_report",
  validation_policy: "pass_fail_score_and_repair_log_required",
  escalation_policy: "p1_if_repair_fails",
};

export const deployAgentContract: AgentContract = {
  agent_name: "deploy_agent",
  agent_class: "deployment",
  version: "1.0.0",
  capabilities: [
    "artifact_deployment",
    "rollback_management",
    "healthcheck_verification",
    "release_recording",
  ],
  input_schema: "ReleaseCandidate",
  output_schema: "DeploymentRecord",
  memory_read_tiers: [MemoryTier.M0, MemoryTier.M1, MemoryTier.M4],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M4],
  allowed_tools: ["github", "vercel", "cloud_provider", "ci_cd"],
  cost_ceiling_usd: 5,
  timeout_ms: 300000,
  retry_policy: { max_attempts: 1, backoff: "none" },
  fallback_policy: "rollback",
  validation_policy: "deployment_url_healthcheck_required",
  escalation_policy: "p0_if_deploy_fails_after_partial_release",
};

export const outreachAgentContract: AgentContract = {
  agent_name: "outreach_agent",
  agent_class: "revenue",
  version: "1.0.0",
  capabilities: [
    "email_sequence_generation",
    "linkedin_outreach",
    "compliance_checking",
    "follow_up_automation",
  ],
  input_schema: "OfferAndICP",
  output_schema: "OutreachSequence",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["llm_gateway", "crm", "email_service"],
  cost_ceiling_usd: 4,
  timeout_ms: 90000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "draft_only_no_send",
  validation_policy: "consent_suppression_and_claims_check_required",
  escalation_policy: "p0_if_compliance_violation",
};

export const salesAgentContract: AgentContract = {
  agent_name: "sales_agent",
  agent_class: "revenue",
  version: "1.0.0",
  capabilities: [
    "lead_scoring",
    "discovery_preparation",
    "objection_handling",
    "proposal_generation",
    "next_action_recommendation",
  ],
  input_schema: "LeadOrDeal",
  output_schema: "SalesAction",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1],
  allowed_tools: ["crm", "proposal_generator", "llm_gateway"],
  cost_ceiling_usd: 5,
  timeout_ms: 120000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "human_sales_review",
  validation_policy: "proposal_requires_scope_price_terms_and_risk",
  escalation_policy: "p1_if_discount_or_contract_exception",
};

export const customerSuccessAgentContract: AgentContract = {
  agent_name: "customer_success_agent",
  agent_class: "revenue",
  version: "1.0.0",
  capabilities: [
    "onboarding_tracking",
    "roi_monitoring",
    "adoption_analysis",
    "churn_risk_detection",
    "expansion_opportunity_identification",
  ],
  input_schema: "CustomerState",
  output_schema: "SuccessPlan",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M3],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M2],
  allowed_tools: ["crm", "support_desk", "llm_gateway"],
  cost_ceiling_usd: 4,
  timeout_ms: 120000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "human_cs_review",
  validation_policy: "churn_risk_and_next_action_required",
  escalation_policy: "p1_if_churn_risk_high",
};

export const revopsAgentContract: AgentContract = {
  agent_name: "revops_agent",
  agent_class: "revenue",
  version: "1.0.0",
  capabilities: [
    "mrr_arr_calculation",
    "cac_ltv_analysis",
    "attribution_tracking",
    "billing_management",
  ],
  input_schema: "RevenueEvent",
  output_schema: "RevenueMetricUpdate",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M3, MemoryTier.M4],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M4],
  allowed_tools: ["stripe", "crm", "analytics_db"],
  cost_ceiling_usd: 2,
  timeout_ms: 60000,
  retry_policy: { max_attempts: 3, backoff: "exponential" },
  fallback_policy: "finance_audit_queue",
  validation_policy: "ledger_balances_required",
  escalation_policy: "p0_if_billing_data_loss",
};

export const complianceAgentContract: AgentContract = {
  agent_name: "compliance_agent",
  agent_class: "governance",
  version: "1.0.0",
  capabilities: [
    "rbac_enforcement",
    "tenant_isolation",
    "consent_management",
    "policy_evaluation",
    "audit_trail",
  ],
  input_schema: "PolicyEvaluationRequest",
  output_schema: "PolicyDecision",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M3, MemoryTier.M4],
  memory_write_tiers: [MemoryTier.M4],
  allowed_tools: ["policy_engine", "audit_log"],
  cost_ceiling_usd: 1,
  timeout_ms: 10000,
  retry_policy: { max_attempts: 1, backoff: "none" },
  fallback_policy: "deny_by_default",
  validation_policy: "decision_reason_required",
  escalation_policy: "p0_if_security_or_privacy_violation",
};

export const observabilityAgentContract: AgentContract = {
  agent_name: "observability_agent",
  agent_class: "operations",
  version: "1.0.0",
  capabilities: [
    "slo_monitoring",
    "workflow_stall_detection",
    "agent_degradation_analysis",
    "dlq_monitoring",
    "cost_anomaly_detection",
    "revenue_incident_detection",
  ],
  input_schema: "MetricEventBatch",
  output_schema: "AlertOrRunbookAction",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M4],
  memory_write_tiers: [MemoryTier.M1, MemoryTier.M4],
  allowed_tools: ["prometheus", "grafana", "alertmanager"],
  cost_ceiling_usd: 1,
  timeout_ms: 30000,
  retry_policy: { max_attempts: 2, backoff: "exponential" },
  fallback_policy: "alert_human_operator",
  validation_policy: "severity_owner_and_runbook_required",
  escalation_policy: "p0_for_security_or_revenue_outage",
};

export const metaAgentContract: AgentContract = {
  agent_name: "meta_agent",
  agent_class: "self_improvement",
  version: "1.0.0",
  capabilities: [
    "failure_diagnosis",
    "improvement_proposal_generation",
    "benchmark_execution",
    "promotion_rollback_recommendation",
  ],
  input_schema: "EvalReport",
  output_schema: "AgentImprovementProposal",
  memory_read_tiers: [MemoryTier.M1, MemoryTier.M2, MemoryTier.M5],
  memory_write_tiers: [MemoryTier.M5],
  allowed_tools: ["evaluation_runner", "prompt_registry", "llm_gateway"],
  cost_ceiling_usd: 12,
  timeout_ms: 300000,
  retry_policy: { max_attempts: 1, backoff: "none" },
  fallback_policy: "no_change",
  validation_policy: "benchmark_delta_and_regression_report_required",
  escalation_policy: "p1_if_agent_class_degraded",
};

export const ALL_CONTRACTS: AgentContract[] = [
  marketScannerContract,
  painDetectorContract,
  opportunityValidatorContract,
  economicAnalystContract,
  smePanelCoordinatorContract,
  productSpecWriterContract,
  taskGraphBuilderContract,
  builderAgentContract,
  qaRepairAgentContract,
  deployAgentContract,
  outreachAgentContract,
  salesAgentContract,
  customerSuccessAgentContract,
  revopsAgentContract,
  complianceAgentContract,
  observabilityAgentContract,
  metaAgentContract,
];
